### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by gbenvenuti**

### CODE REVIEW

**Comment by KoryNunn** [comment]
+1

**Comment by liamoehlman** [comment]
+1

**Comment by MauriceButler** [comment]
+1

**Comment by gbenvenuti** [comment]
conflict now resolved LGTM!

**Comment by gbenvenuti** [comment]
@MatthewLarner where are we at with this? I would love to use this module in my project.  The consensus seems to be positive as they pre-date reactions.

**Comment by MatthewLarner** [comment]
@gbenvenuti I would like to merge this PR. Could you please provide written consent from the author of the asset file.

**Comment by KoryNunn** [comment]
Source: http://one.aap.com.au/#/search/20110526000320815066

**Comment by MatthewLarner** [comment]
Thank you @KoryNunn. As suspected the AAC image website terms and conditions section 4.4 forbid the use of this image.

https://www.aap.com.au/Content/Documents/AAP_Image_Website_Terms_and_Conditions_30_6_2009.pdf

**Pull request closed without merging**
